// <auto-generated />
namespace H4M_Assurance.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CirconsancsConstats : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CirconsancsConstats));
        
        string IMigrationMetadata.Id
        {
            get { return "201806112145262_CirconsancsConstats"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
